config/routes.rb
Rails.application.routes.draw do
  resources :messages

  resources :books do
    post 'delete'
  end
  get '/deleted_books' => 'books#deleted_books', as: :deleted_books

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :editions
  has_many :active_editions, -> { where('editions.deleted_at IS NULL') }, class_name: :Edition 
  accepts_nested_attributes_for :editions

  validates :title, presence: true
  validates :editions,  presence: true

  scope :active_books, -> {
    where(deleted_at: nil)
  }

end

app/models/book_number.rb
class BookNumber < ActiveRecord::Base
  has_many :lending
  belongs_to :edition

  scope :on_loan, -> {
    where(status: 1)
  }
end

app/models/edition.rb
class Edition < ActiveRecord::Base
  belongs_to :book
  has_many :book_numbers

  #validates :book_id, presence: true
  validates :kind, presence: true
  validate :kind_is_not_zero

  private

  def kind_is_not_zero
  	errors.add(:kind, 'is not 0') if kind == '0'
  end
end

app/models/lending.rb
class Lending < ActiveRecord::Base
  belongs_to :book_number
  belongs_to :member


end

app/models/member.rb
class Member < ActiveRecord::Base
  has_many :lendings

end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/book_numbers_controller.rb
class BookNumbersController < ApplicationController

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  respond_to :html

  def index
    @books = Book.active_books
  end

  def show
    @book = Book.find params[:id]
  end

  def new
    @book = Book.new
    @book.editions.build
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      respond_with @book, location: books_path
    else
      respond_with @book.errors, location: book_new_path
    end
  end

  def edit
    @book = Book.find(params[:id])
    @book.editions.build
  end

  def update
    @book = Book.find(params[:id])
    #@book.editions

    if @book.update_attributes(book_params)
      respond_with @book, location: books_path
    else
      render 'edit'
      #respond_with @book.errors, location: book_edit_path
    end
  end


  def delete
    @book = Book.find(params[:book_id])
    if @book.update(deleted_at: Time.now)
      respond_with @book, location: books_path
    else
      respond_with @book.errors, location: book_edit_path
    end
  end

  def deleted_books
    @books = Book.where('deleted_at IS NOT NULL')
  end

  private
    def book_params
      puts params
      params.require(:book).permit(:title, :status, {editions_attributes: [:id, :book_id, :kind]},)
    end

end

app/controllers/lendings_controller.rb
class LendingsController < ApplicationController

end

app/controllers/members_controller.rb
class MembersController < ApplicationController

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:title, :context)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/books/_form.html.haml
= form_for @book, html: { class: "form form-horizontal message" } do |f|
  .form-group
    = f.label :title, class: 'control-label'
    .controls
      = f.text_field :title, class: 'form-control', required: true
    =error_span(@book[:title])
  =f.fields_for :editions do |i|
    //formの追加
    .form-group
      =i.label :kind, class: 'control-label', required: true
      .controls
        =i.text_field :kind, class: 'form-control'
    =i.fields_for :book_numbers do |book_number|
      .form-group
        =book_number.label :status, class: 'control-label'
        .controls
          =book_number.number_field :status, class: 'form-control'

  = f.submit '作成する', class: 'btn btn-primary'
  = link_to 'キャンセル', books_path, class: 'btn btn-default'

app/views/books/_list.html.haml
%table.table.table-striped
  %thead
    %tr
      %th= Book.human_attribute_name(:id)
      %th= Book.human_attribute_name(:title)
      %th= Book.human_attribute_name(:created_at)
      %th= ""
  %tbody
    - @books.each do |book|
      %tr
        %td= book.id
        %td= link_to book.title, book_path(book)
        %td= book.created_at.strftime('%Y-%m-%d')

        %td
          = link_to "edit", edit_book_path(book), class: 'btn btn-default btn-xs'
          = link_to "delete", book_delete_path(book), method: :book_delete, class: 'btn btn-xs btn-danger', data: {confirm: "本当に削除してもよろしいでしょうか？"}

app/views/books/deleted_books.html.haml
.page_header
  %h1='DeletedBooks'
  = link_to "new", new_book_path, class: 'btn btn-primary'
  =render partial: "list"

app/views/books/edit.html.haml
.page-header
  %h1= "Book_edit"
  - if @book.errors.any?
    = @book.errors.full_messages.join
= render "form"

app/views/books/index.html.haml
.page_header
  %h1='Books'
  = link_to "new", new_book_path, class: 'btn btn-primary'
%table.table.table-striped
  %thead
    %tr
      %th= Book.human_attribute_name(:id)
      %th= Book.human_attribute_name(:title)
      %th= Book.human_attribute_name(:status)
      %th= Book.human_attribute_name(:created_at)
      %th= ""
  %tbody
    - @books.each do |book|
      %tr
        %td= book.id
        %td= book.title
        %td= book.status
        %td= book.created_at.strftime('%Y-%m-%d')
        %td
          = link_to "edit", edit_book_path(book), class: 'btn btn-default btn-xs'
          = link_to "delete", book_delete_path(book), method: :book_delete, class: 'btn btn-xs btn-danger', data: {confirm: "本当に削除してもよろしいでしょうか？"}

app/views/books/new.html.haml
.page-header
  %h1= 'Book_new'
= render partial: "form"

app/views/books/show.html.haml
.page_header
  %h1 book_detail

%p
  %strong= Book.human_attribute_name(:title)
  %br
  = @book.title
%p
  %strong= Book.human_attribute_name(:title)
  %br
  = @book.title
%p
  %strong= Book.human_attribute_name(:edition)
- @book.editions.each do |edition|
  = edition.kind
  %br
  貸出可能数
  = edition.book_numbers.on_loan.count
  \/
  = edition.book_numbers.count
  冊
  %br

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Library</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Library"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href="#") Library
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            %li= link_to "Link 1", "/path1"
            %li= link_to "Link 2", "/path2"
            %li= link_to "Link 3", "/path3"
            %li= link_to "Link 3", "/path3"

    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
        .col-lg-3
          .well.sidebar-nav
            %h3 Sidebar
            %ul.nav.nav-list
              %li.nav-header Sidebar
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"
      %footer
        %p &copy; Company 2014

app/views/messages/_form.html.haml
= nested_form_for @message, html: { class: "form form-horizontal message" } do |f|
  .form-group
    = f.label :title, class: 'control-label'
    .controls
      = f.text_field :title, class: 'form-control', required: true
    = error_span(@message[:title])
  .form-group
    = f.label :context, class: 'control-label'
    .controls
      = f.text_field :context, class: 'form-control', required: true
    = error_span(@message[:context])

  = f.submit nil,class: 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), messages_path, :class => 'btn btn-default'

app/views/messages/edit.html.haml
- model_class = Message
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/messages/index.html.haml
- model_class = Message
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:context)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @messages.each do |message|
      %tr
        %td= link_to message.id, message_path(message)
        %td= message.title
        %td= message.context
        %td=l message.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_message_path(message), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), message_path(message), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_message_path, :class => 'btn btn-primary'

app/views/messages/new.html.haml
- model_class = Message
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/messages/show.html.haml
- model_class = Message
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:title) + ':'
  %br
  = @message.title
%p
  %strong= model_class.human_attribute_name(:context) + ':'
  %br
  = @message.context


= link_to t('.back', :default => t("helpers.links.back")), messages_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_message_path(@message), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), message_path(@message), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'